namespace : sanitation
# Common Labels
labels:
  app: "upyog-ui"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "upyog-ui"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "upyog-ui"
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/upyog-ui/"
  readinessProbePath: "/upyog-ui/"

namespace: egov    
extraVolumes: |
  - name: js-injection
    configMap:
      name: upyog-ui-js-injection

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
