{{- with index .Values "cluster-configs" "secrets" "kafka-connect" }}
{{- if index . "elastic-truststore.jks" }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "kafka-connect" "name" }}
  namespace: {{ $ns }}
type: Opaque
data:
  elastic-truststore.jks: {{ index $.Values "cluster-configs" "secrets" "kafka-connect" "elastic-truststore.jks" | quote }}
{{- end }}
---
{{- end }}
{{- end }}
