{{- with index .Values "cluster-configs" "secrets" "upyog-voice-bot" }}
{{- if index . "groq-api-key" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  groq-api-key: {{ index . "groq-api-key" | b64enc | quote }}
  bhashini-api-key: {{ index . "bhashini-api-key" | b64enc | quote }}
  bhashini-user-id: {{ index . "bhashini-user-id" | b64enc | quote }}
  bhashini-auth: {{ index . "bhashini-auth" | b64enc | quote }}
  upyog-basic-auth: {{ index . "upyog-basic-auth" | b64enc | quote }}
{{- end }}
{{- end }}
